### PR TITLE
Sim & AdvantageKit

### PR DESCRIPTION
**Pull request by person4268**
Please squash merge when done

### CODE REVIEW

**Review by alrazzi — APPROVED** [review]
Looks great! 🚢

**Comment by person4268** [comment]
now we just need to find some usable sim constants, the steer pid unusably oscillates lol
(also, did you know these comments update live?)

**Comment by alrazzi** [comment]
definitely next step is getting sim constants. do we need to do any characterization on our swerve chassis for that?

**Comment by person4268** [comment]
thinking just get it into a ballpark where it feels ok, unless sysid can do flywheels

**Pull request merged**
