### PR TITLE
Annotated constants

### PR DESCRIPTION
**Pull request by person4268**
It's quite nice, but leaves me wondering whether this is the most optimal way

do we want to do every field, instead of annotating them individually for instance?

(please squash merge)

### CODE REVIEW

**Review by alrazzi — APPROVED** [review]
Looks good 🚀. Has similar structure to Oblog.

**Comment by alrazzi** [comment]
annotating them individually would be too cumbersome; keep it the way it is now. Btw, I'm assuming you ran it in sim and didn't get any errors (since I didn't run it on my computer).

**Comment by alrazzi** [comment]
are you fine with me deleting the feature branch? Or are you gonna do some more development there?

**Comment by person4268** [comment]
eh, just delete it

also, you currently have to annotate every variable individually lol, i think you misread it, you have to annotate every variable you want published with @NTPublish

**Comment by alrazzi** [comment]
oops kinda skimmed over that if statement. If its only adding @NTPublish and nothing else, then that's fine. I was more so afraid of changing the code to require syntactically long annotations with parameters and what not for different field types.

**Comment by person4268** [comment]
There are two annotations this adds:
@MultiRobotDouble(real=1.0, sim=2.0): When applied to a double, it will have different values assigned depending on whether the robot is running in sim or not. Can be expanded to have a multi-robot application or for other types
@NTPublish: Publishes the variable to NT, following the hieararchy of nested classes, so Constants.Drivetrain.MAX_LIN_VEL would be at Constants/Drivetrain/MAX_LIN_VEL, and it's bidirectional (setting it in NT updates the constant)

**Comment by person4268** [comment]
the justification for MultiRobotDouble is to
1) experiment with the possibility of a shared codebase between robots (so for instance the changes for MAXSwerve won't be super insane maybe? think we'd just need a mechanism to configure which steer/drive classes get instantiated, then make one that'll work for enums)
2) allow for different e.g. pid values if sim isn't calibrated properly

**Pull request merged**
